vich_uploader:
    db_driver: orm


    mappings:
       vol:
           uri_prefix: /images/vol
           upload_destination: '%kernel.project_dir%/public/images/vol'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
